name: 'AWS EC2 Instance State Action'
description: 'Starts, stop, terminates, and reboots EC2 instances'
author: 'TrueMark'
inputs:
  instance-ids:
    required: true
    description: 'Instance IDs to perform action on'
  region:
    required: true
    description: 'AWS region to use'
  action:
    required: true
    description: 'Action to perform: start, stop, reboot, hibernate or terminate'
runs:
  using: 'node16'
  main: 'dist/index.js'
